from pydantic import BaseModel, Field
from typing import Optional, List, Union

# Define the data model for URL queries
class URLSearchQuery(BaseModel):
    url_contains: Optional[str] = Field(None, description="URL contains specific text")
    last_serving_ip: Optional[str] = Field(None, description="Last serving IP address")
    tld: Optional[str] = Field(None, description="Top-Level Domain (TLD)")
    positive_detections: Optional[List[str]] = Field(None, description="Number of positive detections, can include ranges like '20+', '31-'")
    hostname_contains: Optional[str] = Field(None, description="Hostname contains specific text")
    path_contains: Optional[str] = Field(None, description="Path contains specific text")
    query_value_contains: Optional[str] = Field(None, description="Query value contains specific text")
    http_header_contains: Optional[str] = Field(None, description="HTTP header value contains specific text")
    antivirus_label: Optional[str] = Field(None, description="Antivirus label")
    title_contains: Optional[str] = Field(None, description="Title contains specific text")
    categories_contains: Optional[str] = Field(None, description="Categories contain specific text")
    tags: Optional[str] = Field(None, description="Tags associated with the URL")
    last_seen_after: Optional[str] = Field(None, description="Last seen after (YYYY-MM-DD)")
    last_seen_before: Optional[str] = Field(None, description="Last seen before (YYYY-MM-DD)")
    first_seen_after: Optional[str] = Field(None, description="First seen after (YYYY-MM-DD)")
    first_seen_before: Optional[str] = Field(None, description="First seen before (YYYY-MM-DD)")
    last_analysis_after: Optional[str] = Field(None, description="Last analysis after (YYYY-MM-DD)")
    last_analysis_before: Optional[str] = Field(None, description="Last analysis before (YYYY-MM-DD)")
    main_icon_dhash: Optional[str] = Field(None, description="Favicon hash for visual similarity analysis")
    reputation: Optional[List[str]] = Field(None, description="Reputation score, can include ranges like '70+', '-10'")
    times_submitted: Optional[List[str]] = Field(None, description="Times submitted, can include ranges like '3', '4+', '10-'")
    http_response_status: Optional[str] = Field(None, description="HTTP response status code")
    submitter: Optional[str] = Field(None, description="Submitter source (API, web) or country (ISO Alpha-2 code)")
    first_submitter: Optional[str] = Field(None, description="Country of first submitter (ISO Alpha-2 code)")
    category: Optional[str] = Field(None, description="Content category of the domain")
    cookie: Optional[str] = Field(None, description="Cookie value in HTTP response")
    cookie_value: Optional[str] = Field(None, description="Specific cookie key-value pair")
    http_header_key: Optional[str] = Field(None, description="HTTP response header key")
    http_header_value: Optional[str] = Field(None, description="HTTP response header value")
    password_protected: Optional[bool] = Field(False, description="Indicates if the URL is password protected")
    exact_path: Optional[str] = Field(None, description="Exact URL path")
    extension: Optional[str] = Field(None, description="File extension associated with the URL")
    port: Optional[int] = Field(None, description="Port number of the HTTP server")
    query_field: Optional[str] = Field(None, description="Specific query field key")
    query_value: Optional[str] = Field(None, description="Specific query field value")
    redirects_to: Optional[str] = Field(None, description="URL the page redirects to")
    response_code: Optional[str] = Field(None, description="HTTP response code")
    response_positives: Optional[List[str]] = Field(None, description="Number of antivirus detections on response content")
    response_size: Optional[List[str]] = Field(None, description="Size of the content returned, in bytes")
    scheme: Optional[str] = Field(None, description="Protocol scheme (HTTP/HTTPS)")
    title: Optional[str] = Field(None, description="Title contained in the HTML response")
    tracker: Optional[str] = Field(None, description="Analytics tracker used in the URL")
    parent_domain: Optional[str] = Field(None, description="Parent domain of the URL")
    threat_actor: Optional[str] = Field(None, description="Threat actor associated with the URL")
    targeted_brand: Optional[str] = Field(None, description="Brand targeted by phishing engines")
    downloads_windows_executable: Optional[bool] = Field(False, description="Indicates if the URL downloads a Windows executable")
    downloads_document: Optional[bool] = Field(False, description="Indicates if the URL downloads a document")
    is_open_directory: Optional[bool] = Field(False, description="Indicates if the URL is an open directory")
    open_directory_lists_executables: Optional[bool] = Field(False, description="Indicates if the open directory lists executables")
